#!/bin/bash

# $1 is name of the program
# $2 is number of repeats for timer
# $3 is compiler options to compare
# $4 is compiler option

log=.timer.log

tablines() {
    OIFS=$IFS
    IFS=$'\n'
    for line in $1
    do
        echo "    $line"
    done
    IFS=$OIFS
}
comment() {
    OIFS=$IFS
    IFS=$'\n'
    for line in $1
    do
        echo "-- $line"
    done
    IFS=$OIFS
}

run() {
    ./$1 +RTS -p -RTS &>> $log
}
clean() {
    rm $1 $1.o $1.prof &>> $log
}
timer() {
    echo "time of $2 launches:"
    tablines "$(`find ../../.. -path "*exercises/timer"` ./$1 $2)"
}
showprof() {
    echo "profiling:"
    tablines "$(grep total $1.prof | sed 's/^[[:space:]]*//g')"
}
cycle() {
    clean $1
    ghc -prof -o $1 $3 $1.hs &>> $log
    timer $1 $2
    run      $1 
    showprof $1
}
wrappedcycle() {
    comment "$(tablines "$(cycle $1 $2 $4)")"
}

echo "-- without options:"
wrappedcycle $1 $2 $4

for option in $3
 do
    echo "-- with $option:"
    wrappedcycle $1 $2 $3 "$option $4"
 done
