default-target = "wasm32-unknown-unknown"
# this target gives smooth picture when filtering

#default-target = "wasm32-unknown-emscripten"
# emscripten works slower

[cargo-web]
minimum-version = "0.6.0"

[target.wasm32-unknown-emscripten]
link-args = ["-s", "USE_SDL=2"]
