[package]
name = "microservice"
version = "0.1.0"
authors = ["Kirill Taran <kirill.t256@gmail.com>"]

[dependencies]
serde_json = "1.0.22"
env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.14"
log = "0.4.1"
url = "1.7.0"